var EID_val="",ICCID_val="",APDU_a="1",APDU_b="",UPDATA_OK="",APDU_c="",APDU_d="",DP_d="",provisioning_id="",view_provisioning="";function fnGetEid(){"OK"==fnListReaders()&&fnConnect_Card(document.getElementById("ChooseReader").value)&&(fnGetATR(),fnRunAPDU("00a4040409676F74656C6C417070"),fnGetSW(),fnRunAPDU("001A000010"),fnGetSW(),fnGetRetData("EID"),showloading(),"false"==fnCheckICCID()?hiddenLoading():fnGetDP_iccid())}
function fnViewProvisioning(){if("OK"==fnListReaders()&&fnConnect_Card(document.getElementById("ChooseReader").value))if(fnGetATR(),fnRunAPDU("00a4040409676F74656C6C417070"),fnGetSW(),fnRunAPDU("00A9000000"),fnGetSW(),fnGetRetData("provisioning_id"),22<=provisioning_id.length){for(var a=provisioning_id.length/22,b=[],c=0;c<a;c++)b[c]=ChangeNums(provisioning_id.substring(22*c,22*(c+1)).substring(2));fnCardOff();fnFreeReader();alert(b)}else fnCardOff(),fnFreeReader()}
function fnGetProvisioning(){"OK"==fnListReaders()&&fnConnect_Card(document.getElementById("ChooseReader").value)&&(fnGetATR(),fnRunAPDU("00a4040409676F74656C6C417070"),fnGetSW(),fnRunAPDU("00E290000CBF33"+document.getElementById("provisioning_select").value),fnGetSW(),fnGetRetData("provisioning_id"),console.log(ICCID_val.substring(22*i,22*(i+1)).substring(2)+"-----"))}
function fnCheckICCID(){fnRunAPDU("00a4040409676F74656C6C417070");fnGetSW();fnRunAPDU("80E2900002BF2D");fnGetSW();fnGetRetData("ICCID");if(22<=ICCID_val.length)for(var a=ICCID_val.length/22,b=0;b<a;b++){if(ChangeNums(ICCID_val.substring(22*b,22*(b+1)).substring(2)),document.getElementById("ChooseSIMCard").value==ChangeNums(ICCID_val.substring(22*b,22*(b+1)).substring(2)))return alert("Same profile has been downloaded in the SIM card, cannot be download again."),hiddenLoading(),"false"}else alert("No Data");
return"true"}
function fnAjaxAPDU(a,b,c,d){var e="",e=""==b?d?c.substring(d):c:d?b+c.substring(d):b+c;ajax({type:"POST",url:"https://c9dp.roam2free.com:8443/roam2free-dp-service/gsma/rsp2/es9plus/m2m/sendRes",contentType:"application/x-www-form-urlencoded;",async:!1,data:{data:e},beforeSend:function(){},success:function(b){"APDU_a"==a&&(APDU_a=b.responseText,fnRunAPDUBACK("APDU_b",APDU_a,5));"UPDATA_OK"==a&&(UPDATA_OK=b.responseText,fnAjaxAPDU_c1_c4("APDU_c","05",APDU_b,2));"APDU_d"==a&&fnAjaxAPDU("DP_d","",APDU_c)},
error:function(a){alert("There are problems in download profile from server (3)");hiddenLoading()}})}
function fnGetDP_iccid(){var a=(new Date).getTime();ajax({type:"POST",url:"https://c9dp.roam2free.com:8443/roam2free-dp-service/gsma/rsp2/es2plus/downloadOrder",contentType:"application/json;",async:!1,dataType:"json",data:JSON.stringify({orderId:"twtest_"+a,eid:EID_val+"",iccid:document.getElementById("ChooseSIMCard").value}),beforeSend:function(){},success:function(a){200==a.status?ajax({type:"POST",url:"https://c9dp.roam2free.com:8443/roam2free-dp-service/gsma/rsp2/es2plus/confirmOrder",contentType:"application/json;",
async:!1,data:JSON.stringify({eid:EID_val,iccid:document.getElementById("ChooseSIMCard").value,releaseFlag:!0}),beforeSend:function(){},success:function(a){200==a.status?fnAjaxAPDU("APDU_a","03",EID_val):(alert("There are problems in download profile from server (2)"),hiddenLoading())},error:function(a){alert("There are problems in download profile from server (2.1)");hiddenLoading();console.log("error--"+a)}}):(alert("There are problems in download profile from server (1)"),hiddenLoading())},error:function(a){alert("There are problems in download profile from server (1.1)");
hiddenLoading()}})}function fnRunAPDUBACK(a,b,c){b=c?b.substring(c):b;lReturn=myScc.RunAPDU(b);0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."):(fnGetSW(),fnGetRetData(a),fnAjaxAPDU("UPDATA_OK","04",APDU_b,2))}
function fnRunAPDU_C(a,b){b=b.split(",");lReturn=myScc.RunAPDU(b[1]);0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."):(lReturn=myScc.RunAPDU(b[2]),0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."):(lReturn=myScc.RunAPDU(b[3]),0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."):(lReturn=myScc.RunAPDU(b[4]),0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+
lReturn+"\uff09."):(fnGetSW(),fnGetRetData(a),sRes=myScc.GetRetData(),ajax({type:"POST",url:"https://c9dp.roam2free.com:8443/roam2free-dp-service/gsma/rsp2/es9plus/m2m/sendRes",contentType:"application/x-www-form-urlencoded;",async:!1,data:{data:sRes},beforeSend:function(){},success:function(a){-1==a.responseText.indexOf("CTRL")?alert("Failed to update SIM with selected profile"):alert("SIM is updated successfully with selected profile");hiddenLoading()},error:function(a){alert("There are problems in download profile from server (3)");
hiddenLoading()}})))))}function fninputAPDU(a){(a=document.getElementById(a).value)?(lReturn=myScc.RunAPDU(a),0!=lReturn?alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."):(sSW=myScc.GetSW(),fnGetRetData("GetRetData"))):alert("\u8bf7\u8f93\u5165\u6307\u4ee4")}
function fnGetICCID(){if("OK"==fnListReaders()&&fnConnect_Card(document.getElementById("ChooseReader").value))if(fnGetATR(),fnRunAPDU("00a4040409676F74656C6C417070"),fnGetSW(),fnRunAPDU("80E2900002BF2D"),fnGetSW(),fnGetRetData("ICCID"),22<=ICCID_val.length){for(var a=ICCID_val.length/22,b=[],c=0;c<a;c++)b[c]=ChangeNums(ICCID_val.substring(22*c,22*(c+1)).substring(2));fnCardOff();fnFreeReader();alert(b)}else fnCardOff(),fnFreeReader()}
function fnAjaxAPDU_c1_c4(a,b,c,d){a="";a=""==b?d?c.substring(d):c:d?b+c.substring(d):b+c;ajax({type:"POST",url:"https://c9dp.roam2free.com:8443/roam2free-dp-service/gsma/rsp2/es9plus/m2m/sendRes",contentType:"application/x-www-form-urlencoded;",async:!1,data:{data:a},beforeSend:function(){},success:function(a){200==a.status?(APDU_c=a.responseText,fnRunAPDU_C("APDU_d",APDU_c)):(alert("There are problems in download profile from server (3)"),hiddenLoading())},error:function(a){alert("There are problems in download profile from server (1)")}})}
function fnListReaders(){var a=document.getElementById("ChooseReader");a.innerHTML="";try{s=new String(myScc.ListReaders())}catch(d){alert("Please use IE browser, install and activate LPA plugin.");hiddenLoading();return}cars=s.split("||");if(1==cars.length)alert("There is no SIM card reader found."),hiddenLoading();else{for(var b=0;b<cars.length-1;b++){var c=document.createElement("OPTION");c.text=cars[b];c.value=cars[b];a.options.add(c)}return"OK"}}
function fnSetReader(a){lReturn=myScc.SetReader(a);return 0!=lReturn?(alert("There are problems reading SIM card reader."),hiddenLoading(),!1):!0}function fnConnect_Card(a){lReturn=myScc.SetReader(a);if(0!=lReturn)alert("There are problems reading SIM card reader."),hiddenLoading();else if(lReturn=myScc.CardOn(),0!=lReturn)alert("There are problems connected to SIM card reader."),hiddenLoading();else return!0}
function fnCardOn(a){lReturn=myScc.CardOn();0!=lReturn&&(alert("There are problems connected to SIM card reader."),hiddenLoading())}function fnGetATR(){sATR=myScc.GetATR()}function fnRunAPDU(a){lReturn=myScc.RunAPDU(a);0!=lReturn&&(alert("There are problems in communicating with SIM card\uff08"+lReturn+"\uff09."),hiddenLoading())}
function fnGetSW(){sSW=myScc.GetSW();if(9E3!=sSW){if("61"==sSW.substring(0,2)||"91"==sSW.substring(0,2))fnRunAPDU("00C00000"+sSW.substring(2)),fnGetSW();"6A84"==sSW&&(alert("Cannot download profile to SIM card. There are already 10 profiles in SIM card. "),hiddenLoading())}}
function fnGetRetData(a){sRes=myScc.GetRetData();if("EID"==a)return EID_val=sRes;if("ICCID"==a)return ICCID_val=sRes;if("APDU_b"==a)return APDU_b=sRes;if("APDU_d"==a)return APDU_d=sRes;if("provisioning_id"==a)return provisioning_id=sRes}function fnGetRetData_value(){return sRes=myScc.GetRetData()}function fnCardOff(){lReturn=myScc.CardOff();0!=lReturn&&(alert("There are problems ejecting SIM card / card reader"),hiddenLoading())}
function fnFreeReader(){lReturn=myScc.FreeReader();0!=lReturn&&(alert("There are problems ejecting SIM card reader"),hiddenLoading())}
function ajax(a){var b={type:a.type||"GET",url:a.url||"",async:a.async||"true",data:a.data||null,dataType:a.dataType||"text",contentType:a.contentType||"application/x-www-form-urlencoded",beforeSend:a.beforeSend||function(){},success:a.success||function(){},error:a.error||function(){}};b.beforeSend();var c=createxmlHttpRequest();try{c.open(b.type,b.url,b.async)}catch(d){console.log(d);alert("There are problems in download profile from server (0).");hiddenLoading();return}c.setRequestHeader("Content-Type",
b.contentType);c.send(convertData(b.data));c.onreadystatechange=function(){4==c.readyState&&(200==c.status?b.success(c):b.error(c))}}function createxmlHttpRequest(){return new XMLHttpRequest}function convertData(a){if("object"===typeof a){var b="",c;for(c in a)b+=c+"="+a[c]+"&";return b=b.substring(0,b.length-1)}return a}function ChangeNums(a){a=a.split("");for(var b=[],c=0;c<a.length;c++)b[c]=0!=c%2?a[c-1]:a[c+1];return b.join("")};